### ISSUE TITLE
Query syntax

### ISSUE THREAD

**Issue by reetp** [tsolucio/coreBOSDocumentation#4]
I found it was very difficult to understand the varying query syntaxes. One of those things that if you know, it is obvious. But if you don't.....

Here are my notes. I *believe* they are about right, but there could be issues.

All queries use the vTiger list type module (I think!) in the FROM and WHERE sections

One thing I wasn't sure about is that there are two WS functions.... 

'query' and 'getrelatedrecords'

Do you only need to use 'query' for all the query types below, or you need both ? ?

I have the following for Parameters (both work !):

Simple query:
        $params = array(
            "sessionName" => $this->token,
            "operation" => "query",
            "query" => $queryParamaters
        );

Related Query
        $params = array(
            "sessionName" => $this->token,
            "operation" => "getRelatedRecords",
            "id" => $docID,
            "module" => $module,
            "relatedModule" => $relModule,
            "queryParameters" => json_encode($queryParameters)
        );

This is a note of the 3 query formats in the order they are processed as far as I can tell.

==================================================================

1. Related modules

When a query is sent to the webservice query API it looks for the string “related.”
If this string is found we apply the Related Entity Query Syntax.

select * from projecttask where related.project=30x144
select * from projecttask where related.project=30x144 and projecttaskname='dsf'
select * from documents where related.accounts=3x12
select * from documents where filelocationtype='E' and related.contacts=4x22
select * from Documents where (related.Contacts='4x22') AND (filelocationtype LIKE '%I%') LIMIT 5;
select * from modcomments where related.helpdesk=9x114
select * from modcomments where related.helpdesk=9x114 and commentcontent like 'hdcc%'
select * from products where related.products=6x58 // only product children are accessible with this syntax
select * from products where related.contacts=4x22  // only directly related products
select * from products where related.contacts=4x22 and productcategory='Software'  // only directly related products
select * from Products where related.Contacts='4x22' LIMIT 5;
select * from Products where related.Contacts='4x22' order by productname LIMIT 5;

==================================================================

2. Extended syntax - not related

If the string 'related' is not found we look for “not in”, “not null”, “.” or “(”.
None of these strings are supported by the query syntax inherited from vtiger CRM so we apply the Extended QueryGenerator syntax.

SELECT projectname,modifiedtime
FROM project
where projectname like '%cap%' and (modifiedtime>'2016-06-30 19:11:59' or modifiedtime<'2016-07-30 19:11:59')

SELECT * 
FROM project
where projectname like '%cap%' and (modifiedtime>'2016-06-30 19:11:59' or modifiedtime<'2016-07-30 19:11:59')

==================================================================

3. Original VQL syntax (no 'related')

select * | <column_list> | <count(*)>
from <object>
[where <conditionals>] 
[order by <column_list>] [limit [<m>, ]<n>];

SELECT * FROM Products 
where productname='sample' LIMIT 10

column_list: comma separated list of field names.
object: type name of the WS object

conditionals: condition operations or in clauses or like clauses separated by 'and' or 'or' operators these are processed from left to right. There are no grouping that is bracket operators (Copied but not sure what this means ??)

conditional operators: <, >, <=, >=, =, !=.

**Comment by joebordes** [comment]
I added this to the wiki.

Thanks!
