### ISSUE TITLE
Displaytype 4: mention context variable

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/coreBOSDocumentation#5]
https://corebos.com/documentation/doku.php?id=en:devel:field_structure&s[]=typeofdata

Explains the display types, but an important aspect is that the code altering fields should set the $from_wf context variable or the code won't be able to alter the field. I think we should mention that in the text

**Comment by joebordes** [comment]
I added a note to the displaytype 4 line, see what you think

**Comment by Luke1982** [comment]
Perfect!
